### PR TITLE
Fix about pages

### PR DESCRIPTION
**Pull request by solazio**

### CODE REVIEW

**Review by tbille — APPROVED** [review]

**Comment by tbille** [comment]
noooo @anthonydillon what is wrong??

**Comment by anthonydillon** [comment]
The only thing that needs to change is the word Overview to About in the navigation. I'll links and URLs are right already

**Comment by tbille** [comment]
ok @solazio can you revert and update it?

**Comment by solazio** [comment]
@anthonydillon it's changed to be "About" https://github.com/canonical-web-and-design/juju.is/pull/136/files#diff-8944b57466f08564caa53a1988261ae0R145

**Pull request merged**
