### PR TITLE
Add hero typer to homepage

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Add hero typer to homepage

## QA
- Check out the demo
- Ensure the animation of the words match charmhub
- This sites words should be:
  - VM workloads
  - Operators
  - Hybrid cloud
  - Multi-cloud
  - Integration
  - Data
  - Observability
  - Identity
  - Applications
  - Sprawl

### CODE REVIEW

**Comment by Roadmaster** [comment]
I'm concerned this was added without considering input from designers - I am not one, I'm a lowly engineer and I found the typing effect confusing and distracting (I happen to glance at the page when the text has been deleted, the page will seem incomplete - then confusingly text starts appearing. And if I go back to the page later the text will have changed).

I believe the typing effect is gimmicky and doesn't add much value. 

That said, consider this just an opinion - in the end I have no say in what goes into these pages.

**Comment by anthonydillon** [comment]
Response from David Booth:

>  Let’s get it done & revisit it later, with feedback from target audiences.

**Review by pmahnke — APPROVED** [review]
+1

**Comment by pmahnke** [comment]
@anthonydillon does this have points or part of an epic?

**Comment by anthonydillon** [comment]
Good point, I'll assign some. It was a side request so slipped the net.

**Pull request merged**
