### PR TITLE
Update site logo to link to home page

### PR DESCRIPTION
**Pull request by kevmgb**
Update site logo to link to home page

QA
- Open demo and go to templates/partials/_navigation.html
- Check site logo links to homepage

Fixes canonical-web-and-design/juju.is#216

## Done

[List of work items including drive-bys]

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8041
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #

## Screenshots

[if relevant, include a screenshot]

### CODE REVIEW

**Comment by danielmutis** [comment]
I think the best behaviour for this is that the logo links back to the home of the site you are on. So if the user is in Charmhub it links to the homepage, and on juju.is the same.

**Comment by anthonydillon** [comment]
@danielmutis that is what @kevmgb has done here. We will need a similar change in Juju.is.

**Comment by kevmgb** [comment]
Yes, a similar change needs to be made on the charmhub site. This only directs you to the juju.is homepage.

**Comment by anthonydillon** [comment]
Sorry yes, that way round. Thanks @kevmgb

**Review by steverydz — APPROVED** [review]

**Pull request merged**
