### PR TITLE
Update copy on k8s survey page

### PR DESCRIPTION
**Pull request by steverydz**
## Done
Update the copy on the k8s survey report

## QA
- Go to https://juju-is-272.demos.haus/cloud-native-kubernetes-usage-report-2021
- Check that Alex's change requests in [the copy doc](https://docs.google.com/document/d/1PEcz_9tFvzrvX5U5pBQFqHKC_0wfb8wtE6KD9HEa_Ls/edit#) have been made (please tick them off)

### CODE REVIEW

**Review by sowasred2012 — COMMENTED** [review]
Screenshot from 2021-06-23 16-52-10
Code looks good, but Dilbert image linked to in the doc is cut off on the right hand side

**Review by sowasred2012 — CHANGES_REQUESTED** [review]
Dilbert woes

**Comment by steverydz** [comment]
@sowasred2012 I've made a separate issue for the Dilbert image https://github.com/canonical-web-and-design/juju.is/issues/275

so if you're good we can merge this?

**Review by sowasred2012 — APPROVED** [review]
Approving, Dilbert being fixed separately

**Pull request merged**
