### PR TITLE
Update illustrations on the homepage

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Update illustrations on the homepage

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8041
- See that it [the design](https://user-images.githubusercontent.com/9105999/94912434-8a356b80-049f-11eb-9eba-9acfe3c461cd.png) for the images provided.

## Issue / Card
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1425

## Screenshots
image

### CODE REVIEW

**Review by hatched — CHANGES_REQUESTED** [review]
Should these use the image module instead of the `img` tag directly?

Also the `alt`s are empty.

**Comment by anthonydillon** [comment]
Yeah could include image module. A lot of the images adds no value to the content so better to be blank but the logo ones should have alts.

**Comment by anthonydillon** [comment]
@hatched thanks.

Converted all the images to image-module and added alt content.

**Review by hatched — APPROVED** [review]
Thanks for the updates!

**Comment by anthonydillon** [comment]
@spencerbygraves would you mind reviewing this one please?

**Review by spencerbygraves — CHANGES_REQUESTED** [review]
@anthonydillon thanks, one small issue I can see. The dashboard image is appearing twice:

image

**Comment by anthonydillon** [comment]
@spencerbygraves sorry about that. Fixed.

**Comment by spencerbygraves** [comment]
@anthonydillon thanks.

**Comment by anthonydillon** [comment]
@spencerbygraves cheers, can you approve do I can merge it?

**Review by spencerbygraves — APPROVED** [review]

**Pull request merged**
