### PR TITLE
Remove the code copyable component with code snippet

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Remove the code copyable component with code snippet

## QA
- Go to the homepage and scroll to the "Getting started" section
- See that the code snippets don't have copy buttons but you can highlight the text and copy it

Fixes https://github.com/canonical-web-and-design/juju.is/issues/9

## Screenshot
Screenshot_2019-11-06 Juju - The simplest way to deploy and maintain applications in the cloud

### CODE REVIEW

**Comment by clagom** [comment]
Hey Ant I wonder if we can do something more similar to what I had put in the issue? The part with $ seems to be a clickable item. @spencerbygraves maybe you can have a look?

**Comment by anthonydillon** [comment]
@clagom sure, was trying to keep it close to Vanilla. I'll update https://dqlite.io/ with what we decide here.

**Comment by clagom** [comment]
I had a chat with @spencerbygraves, if for tomorrow we could go just with the plain text without box or else, and we need to tackle this later on as a Vanilla option.

**Comment by anthonydillon** [comment]
@clagom sure, done.

**Comment by spencerbygraves** [comment]
@anthonydillon can we remove the white background please, and align the $ and text left. Thanks.

**Comment by anthonydillon** [comment]
@spencerbygraves done

**Comment by spencerbygraves** [comment]
@anthonydillon thanks 👍

**Comment by anthonydillon** [comment]
@barrymcgee do you mind reviewing this one please

**Comment by barrymcgee** [comment]
@anthonydillon Fix up the tests and good to go.

**Pull request merged**
