### PR TITLE
Report side navigation

### LINKED ISSUE #300: Add accordion and scroll spy to report page side navigation

### PR DESCRIPTION
**Pull request by steverydz**
## Done
Added accordions and scroll spy to side navigation

## QA
- Go to https://juju-is-299.demos.haus/cloud-native-kubernetes-usage-report-2021
- Click the headings in the side nav and check that they toggle their menus
- Scroll in the page and check that the section is highlighted in the navigation
- **Note**: The accuracy of this depends on the length of each section and how fast you scroll

## Issue
Fixes #300

### CODE REVIEW

**Comment by jkfran** [comment]
All good but when I click on the last item of a group, it expands the next group. It happens with large screens

**Comment by steverydz** [comment]
@jkfran it should be better now

**Review by sowasred2012 — CHANGES_REQUESTED** [review]
If I open, close, then try to open a section, it does not open the second time unless I click a different section and go back to the original section:

Peek 2021-07-05 09-52

**Comment by steverydz** [comment]
@sowasred2012 fixed

**Review by sowasred2012 — APPROVED** [review]
LGTM

**Comment by steverydz** [comment]
@danielmutis I'm going to merge this as David and Alex are happy with it. We can address any design concerns separately.

**Pull request merged**
