### PR TITLE
K8s survey page

### LINKED ISSUE #269: Build k8s survey page
New page URL: juju.is/cloud-native-kubernetes-usage-report-2021

**Zeplin**
https://app.zeplin.io/project/606203889af57e12287b5308/screen/60ca0ee03cc6b0bc46afaa93

**Copy docs change:**
https://docs.google.com/document/d/1PEcz_9tFvzrvX5U5pBQFqHKC_0wfb8wtE6KD9HEa_Ls/edit#heading=h.95ov3r28x4pf

**Adding to navigation juju.is**
Ensure we also change the navigation in juju.is to include a link to this new page under "learn" we will have:

RESOURCES
[Kubernetes & Cloud Native Operations Report](juju.is/cloud-native-kubernetes-usage-report-2021)

**Adding to navigation ubuntu.com meganav**
https://docs.google.com/document/d/1ry3UzUJ5_danMmo1hjbI1cX6wfMY9PIlO8YWIDlw7OI/edit#heading=h.g5tpr1dg5gaq @steverydz might be easier for you to do this too if you don't mind? so we get the timings right with the launch

### PR DESCRIPTION
**Pull request by steverydz**
## Done
Built a page for the k8s survey results

## QA
- Go to https://juju-is-270.demos.haus/cloud-native-kubernetes-usage-report-2021
- Compare to [the copy doc](https://docs.google.com/document/d/1PEcz_9tFvzrvX5U5pBQFqHKC_0wfb8wtE6KD9HEa_Ls/edit#)

## Issue
- Fixes #269

### CODE REVIEW

**Comment by spencerbygraves** [comment]
Thanks @steverydz, the bios are looking good.

On the two that I can see, one has a max width on the copy and the other doesn't. That also happens on the Intro vs Key takeaways section. It's also on the live site so I suspect there's a problem there somewhere. Any idea why it's applied sometimes and not others?

I'll need to supply the logos, generally I've made them 40px high and centred vertically to the image and text on the left.

**Comment by steverydz** [comment]
@spencerbygraves Vanilla has a max width for copy which often doesn't span the full width. I think @lyubomir-popov knows the reasoning behind it. We can override it but we should come to a consensus as this problem crops up all the time.

**Comment by spencerbygraves** [comment]
@steverydz thanks, just wondering why it's on one bio but not the other.

**Comment by lyubomir-popov** [comment]
@steverydz you can use the class `measure--p` o make sure lists that contain text also conform to the paragraph max width. We don't do this by default because lists are used for many things other than text, e.g. navigation. 

But if you have just text, and because it's in a list it ends up longer than paragraphs above/under it, I recommend applying `measure--p` to it.

**Comment by DaBoCanon** [comment]
title: replace "survey" with "report" please

**Comment by jkfran** [comment]
Is it fine for the "Conclusion" link on the navigation not to be clickable?
image

**Review by jkfran — APPROVED** [review]
LGTM

**Comment by jkfran** [comment]
@steverydz for the **Industry expert bios** should we use a different default image for Ken Sipe and James Strachan?

**Pull request merged**
