### PR TITLE
Build the about devsecops page

### PR DESCRIPTION
**Pull request by anthonydillon**
## QA
- Go to http://0.0.0.0:8041/about/devsecops
- Check the content matches the [copy doc](https://docs.google.com/document/d/10tjWftKVRrmsUn9R5vSLlRtLS0o0nwBbKA4Av5m840w/edit#)

Fixes https://github.com/canonical-web-and-design/juju.is/issues/100

### CODE REVIEW

**Comment by hatched** [comment]
Could you increase the width of the sidebar, or update the label so it doesn't wrap over 3 lines?

Screen Shot 2020-09-15 at 10 00 21 PM

**Comment by hatched** [comment]
After rebasing with the wider column, maybe instead you could indent anything that wraps? Right now it looks like there are two items there "Community-driven" and "DevSecOps

Screen Shot 2020-09-15 at 10 28 31 PM

**Comment by anthonydillon** [comment]
This is ok to land as it needs further work.

**Comment by anthonydillon** [comment]
@hatched let me know

**Review by hatched — APPROVED** [review]

**Pull request merged**
