### PR TITLE
Add scroll padding to k8s report

### LINKED ISSUE #273: Headings are hidden behind fixed header
When clicking links in the side nav on https://juju.is/cloud-native-kubernetes-usage-report-2021, the section headings are hidden behind the fixed. header

### PR DESCRIPTION
**Pull request by steverydz**
## Done
Fixed hidden headings under fixed header

## QA
- Go to https://juju-is-276.demos.haus/cloud-native-kubernetes-usage-report-2021
- Click the links in the side navigation
- Check that the headings for each section are not hidden under the fixed header

## Issue
Fixes #273

### CODE REVIEW

**Review by bethcollins92 — APPROVED** [review]
LGTM 👍🏼

**Comment by sowasred2012** [comment]
I have mixed results with this - if the page is scrolled all the way to the top, clicking any link in the side nav will jump to the correct section, but the heading will be hidden. If I then click another link in the side nav, it'll work as intended (i.e. I can see the heading), but if I scroll back to the top and click another link, it'll be hidden.

**Comment by bethcollins92** [comment]
@sowasred2012 good spot!

**Comment by steverydz** [comment]
@sowasred2012 I agree - but I think this will do as a quick fix given that this needs to be live asap

We need to address this problem once and for all though, seeing as we seem to use fixed headers everywhere

**Pull request merged**
